#%%
list_v2003=["Index","Foodstuffs","Cereals and cereal products","Meat and Poultry","Fish and crustaceans","Milk and dairy products","Eggs","Cooking oil and fats","Fresh vegetables","Preserved and canned vegetables","Legumes and tubers","Fresh fruits","Preserved and canned fruits","Nuts, peanuts, seeds","Sugars and sugar preparations","Beverages","Foodstuffs, other","Tobacco","Out-of-home meals","Fabrics, clothing and footwear","Men's fabrics","Women's fabrics","Men's apparel","Women's apparel","Tailoring","Footwear","House and related items","Home repairs","Rents","Water supply expenditure","Fuel and Power","Home furniture","Furniture and carpet","Home furnishings","Small home appliances","kitchenhouse & tabletualis","Household small items","Home services","Basic home appliances","Medical care","Medical care expenses","Other medical expenses","Medicines","Transport and telecommunications","Private transport means","Operation of private transport means","Public transport fees","Telecommunications and related costs","Education and entertainment","Entertainment expenses","Education expenses","Entertainment devices","Other expenses and services","Personal hygiene and care items","Personal goods","Other expenses and services"]
list_2012_1014 =['General Index', 
'FOOD AND BEVERAGES', 
'FOOD',
'BEVERAGES ',
'TOBACCO ',
'TOBACCO', 
'CLOTHING AND FOOTWEAR',
'CLOTHING',
'FOOTWEAR',
'HOUSING, WATER, ELECTRI-CITY',
'GAS AND OTHER FUELS GAY',
'RENTALS FOR HOUSING',
'MAITENANCE OF THE DEWELLING',
'WATER SUPPLY & OTHER SERVICES', 
'ELECTRICITY, GAS AND OTHER FUELS', 
'FURNISHINGS, HOUSEHOLD', 
'EQUIPMENT AND MAINTENANCE',
'FURNITURE & CARPETS.', 
'HOUSEHOLD TEXTILES',
'HOUSEHOLD APPLIANCES', 
'HOUSEHOLD UTENSILS',
'TOOLS FOR HOUSE & GARDEN',
'GOODS FOR HOUSEHOLD',
'MAINTENANCE',
'HEALTH',
'MEDICAL PRODUCTS & EQUIPMENT', 
'OUTPATIENT SERVICES',
'HOSPITAL SERVICES', 
'TRANSPORT',
'PURCHASE OF VEHICLES', 
'OPERATION OF TRANSPORT',
'EQUIPMENT',
'TRANSPORT SERVICES', 
'COMMUNICATION',
'POSTAL SERVICES',
'TELEPHONE AND TELEFAX EQUIPMENT',
'TELEPHONE AND TELEFAX SERVICES',
'RECREATION AND CULTURE',
'AUDIO, PHOTO & INFO. EQUIPMENT',
'OTHER RECREATION & CULTURE GOODS',
'OTHER RECREATIONAL GOODS',
'RECREATIONAL & CULTURAL SERVICES',
'NEWSPAPERS, BOOKS & STATIONERY',
'PACKAGE HOLIDAYS',
'EDUCATION',
'PRE-PRIMARY & PRIMARY EDUCATION',
'SECONDARY&INTERMEDIATE EDUCATION',
'POST-SECONDARY EDUCATION',
'TERTIARY EDUCATION',
'RESTAURANTS AND HOTELS',
'CATERING SERVICE',
'ACCOMMODATION SERVICES',
'MISCELLANEOUS GOODS AND SERVICES',
'PERSONAL CARE',
'PERSONAL EFFECTS N.E.C.',
'SOCIAL PROTECTION',
'INSURANCE',''
'FINANCIAL SERVICES N.E C.',
'OTHER SERVICES N.E'] # check the names in the rows coz not all of them in the same line
